spring.application.name=credito-consulta-api
spring.datasource.url=jdbc:mariadb://localhost:3306/credito_db?serverTimezone=America/Sao_Paulo&useSSL=false
spring.datasource.username=root
spring.datasource.password=Admin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.flyway.repair-enabled=true
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

